print('===== Challenge 04 =====')

some = input('Write something.\n')

print(type(some))
print(some.isalnum())
print(some.isalpha())
print(some.isascii())
print(some.isdecimal())
print(some.isdigit())
print(some.isidentifier())
print(some.islower())
print('oi',some.isnumeric())
print(some.isprintable())
print(some.isspace())
print(some.istitle())
print(some.isupper())
